### ISSUE TITLE
triple-z circles not round

### ISSUE THREAD

**Issue by jappie1210** [ankurv2k6/tiny-m-tri-zero#1]
Hi,

looking forward to using this mod on my yet-to-build tiny m, but i noticed the holes in quite a few parts look ellipsoid, not round. for instance on back-belt-idler-2;

![image](https://github.com/user-attachments/assets/323116be-1893-4be2-8fdc-8e63cd7f249a)

did something go wrong in the scaling of the stl?

kind regards,
jasper

**Comment by Andrez092** [comment]
I think this will help you.
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)
